sudo: required

language: go

go:
    - 1.10.x

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - clang-3.5
        - g++
        - build-essential
        - libopencv-dev
        - libatlas-base-dev

before_install:
    - source travis/env.sh
    - sudo apt-get update
    - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
    - chmod +x $GOPATH/bin/dep
install:
    # dep
    - dep ensure
    - travis/install.sh

script:
    #TODO fix mxnet building in travis
    - go build ./examples/single/single.go

