sudo: required

language: go

go:
    - 1.7

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - clang-3.5
        - g++
        - build-essential
        - libopencv-dev
        - libatlas-base-dev
    
before_install:
    - source travis/env.sh
    - sudo apt-get update

install:
    # dep
    - travis/install.sh

script:
    #TODO fix mxnet building in travis
    #- go build ./examples/flowers/predict.go
     - echo "TODO"

