sudo: required

language: go

go:
    - 1.10.x

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - clang-6.0
        - g++
        - build-essential
        - libopencv-dev
        - libatlas-base-dev

before_install:
    - source travis/env.sh
    - sudo apt-get update

install:
    # dep
    - travis/install.sh

script:
    #TODO fix mxnet building in travis
    - go build ./examples/single.go

